apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: expense
  # These labels for deployment resource. 
  labels:
    app: mysql
    tier: mysql
    purpose: expense
spec: 
  # Modify the replicas number according to our use case.
  replicas: 1
  selector:
  # Replicaset use these labels to find the pods for creating desired number of replicas.
    matchLabels:
      app: mysql
      tier: mysql
      purpose: expense
  # Pod Template
  template:
    metadata:
      labels: 
        app: mysql
        tier: mysql
        purpose: expense
    spec: 
      containers:
      - name: mysql
        image: joindevops/mysql:1.0.0        
